#!/bin/sh
[ "$ACTION" = ifup ] || exit 0
`route -A inet6 add default gateway $(ip -6 route | grep default | awk 'NR==1' | awk  '{print $5}') dev $(ip -6 route | grep default | awk 'NR==1' | awk '{print $7}')`