#!/usr/bin/env bash

day=`date '+%Y%m%d'`
imgfile=https://github.com/nieningproj/AutoBuild_Openwrt/releases/download/newifi_D2/AutoBuild-d-team_newifi-d2-$day.bin
md5file=https://github.com/nieningproj/AutoBuild_Openwrt/releases/download/newifi_D2/AutoBuild-d-team_newifi-d2-$day.detail
if [[ `curl $imgfile` == 'Not Found' ]]; then
    day=$(($day-1))
fi
imgfile=https://github.com/nieningproj/AutoBuild_Openwrt/releases/download/newifi_D2/AutoBuild-d-team_newifi-d2-$day.bin
md5file=https://github.com/nieningproj/AutoBuild_Openwrt/releases/download/newifi_D2/AutoBuild-d-team_newifi-d2-$day.detail
if [[ `curl $imgfile` == 'Not Found' || `curl $md5file` == 'Not Found' ]]; then
    echo '文件验证错误！！！'
    exit 2
fi
cd /tmp
rm -rf AutoBuild-d-team_newifi*.bin AutoBuild-d-team_newifi*.detail
wget $imgfile
wget $md5file
md5file_md5=`cat AutoBuild-d-team_newifi-d2-$day.detail | grep MD5 | awk -F ':' '{print $2}'`
md5=`md5sum AutoBuild-d-team_newifi-d2-$day.bin | awk 'NF=1'`
file=AutoBuild-d-team_newifi-d2-$day.bin
if [[ "$md5file_md5" == "$md5" ]];then
    echo '下载成功'
else
    echo '文件下载错误！！！'
    exit 2
fi
if [[ "$1" == '-n' ]];then
    echo -n "是否确认不保留配置升级(Y/N)?"
    read key
    if [[ "$key" == "Y" || "$key" == "y" ]]; then
        sysupgrade -n $file
    fi
    exit
else
    echo -n "是否确认升级(Y/N)?"
    read key
    if [[ "$key" == "Y" || "$key" == "y" ]]; then
        sysupgrade $file
    fi
    exit
fi