# This is a basic workflow to help you get started with Actions

name: Build_X86_64

# The type of start
on:

  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'

  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

# define workflow
jobs:
  build:
    runs-on: ubuntu-18.04

    # define steps
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt upgrade
          sudo apt-get -y install build-essential asciidoc \
          binutils bzip2 gawk gettext git libncurses5-dev \
          libz-dev patch python3 python2.7 unzip zlib1g-dev \
          lib32gcc1 libc6-dev-i386 subversion flex uglifyjs \
          git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev \
          texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev \
          autoconf automake libtool autopoint device-tree-compiler \
          g++-multilib antlr3 gperf wget curl swig rsync
          sudo -E apt-get clean

      - name: Clone source
        env:
          REPO_URL: https://github.com/coolsnowwolf/lede
          REPO_BRANCH: master
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          echo "src-git helloworld https://github.com/fw876/helloworld" > feeds.conf.default
          echo "src-git openclash https://github.com/vernesong/OpenClash" > feeds.conf.default
          echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" > feeds.conf.default


      - name: Update & Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Gen Config
        env:
          CONFIG_FILE: 'x86_64.config'
        run: |
          make defconfig

      - name: Download package
        working-directory: ./openwrt
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;  
        
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}   

      - name: Build firmware
        working-directory: ./openwrt
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s      

      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt
          path: openwrt  